### PR TITLE
Use nf-core template for the pipeline to facilitate standardisation

### PR DESCRIPTION
**Pull request by abhi18av**
With the immense momentum behind `nf-core` pipeline and module ecosystem, it is worth moving from our own custom template to a more standardized approach.

This PR marks this transition to the template.

### CODE REVIEW

**Comment by Mxrcon** [comment]
Hey @abhi18av, now that we standardized the pipeline into nf-core template inside the `nf-core-mtbseq` folder, is it time to merge from the folder to outside? so we only work on one version now? perhaps testing with some files

**Comment by abhi18av** [comment]
Thanks for making the push on this template transition - taking a look at this now Davi!

**Comment by Mxrcon** [comment]
@abhi18av the modules are at nf-core standardzation, but we need to stabilish the mtbseq-nf main workflow, converting it from the old version to the new.

**Comment by abhi18av** [comment]
Thank you so much for your dedication and push on this PR @Mxrcon ! 🎉 💚

**Pull request merged**
